# Generated by Django 5.1.3 on 2025-01-12 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bee_created_at_bee_img_bee_return_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
